config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :sessions

  resources :users do
    resources :high_levels
  end

  resources :high_levels do
    resources :one_month_goals
  end

  resources :one_month_goals do
    resources :activities
  end

  resources :activities

  get 'activities/:id/complete' => 'activities#complete', as: 'activities_complete'

  get 'users' => 'users#index'
  get 'welcome' => 'welcome#index'
  get 'stream' => 'welcome#stream'
  delete 'logout' => 'sessions#destroy'
  get 'send_mail' => 'activities#current_activity'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def new
  end

  def index
  end

  def stream
    # This is the user activity stream
    @stream = {}
    @users = User.all

    @users.each do |usr|
      usr.high_levels.each do |hlg|
        day = hlg.updated_at.to_i
        hlg.check
        @stream[day] = [hlg, usr] if hlg.done
        hlg.one_month_goals.each do |omg|
          day = omg.updated_at.to_i
          omg.check
          @stream[day] = [omg, usr] if omg.done
            omg.activities.each do |act|
              day = act.updated_at.to_i
              @stream[day] = [act, usr] if act.done
            end
        end
      end
    end
    @stream = @stream.sort { |x,y| y<=>x}
  end

  def landing

  end

end

app/views/welcome/index.html.erb
<body id="page-top">
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <img src="<%= asset_path("31178_Wynning_Logo_PB.png") %>" class="img-responsive" alt="">

                <hr>
                <p>Start Living the Life of Your Dreams!</p>
                <!-- <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a> -->
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Your Dreams, Made Possible!</h2>
                    <hr class="light">
                    <p class="text-faded">The secret of getting ahead is getting started. The secret of getting started is breaking your long, complex, overwhelming goals into small, manageable chunks. Use Sub goal feature to chunk it down and stop procrastination</p>
                    <% if current_user %>
                      <%= link_to "My Dashboard", current_user, :class => "btn btn-default btn-xl wow tada" %>
                    <% else %>
                      <a href="/users/new" class="btn btn-default btn-xl wow tada">Get Started!</a>
                    <% end %>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">At Your Service</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
                        <h3>15 Minutes a day</h3>
                        <p class="text-muted">In as little as 15 minutes of focused action, you can realize your dreams!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>Stay Reminded</h3>
                        <p class="text-muted">Sign up to get email and text reminders each day.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                        <h3>See how others have achieved their goals</h3>
                        <p class="text-muted">If they can do it, so can you!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                        <h3>Get inspired</h3>
                        <p class="text-muted">See what other people are accomplishing and go for it!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- <%= asset_path('heromenu.png') %> -->

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="<%= asset_path("Pyramids-3.jpg") %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">

                                </div>
                                <div class="project-name">

                                    Visit the Pyramids
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="<%= asset_path("startbix.jpg") %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">

                                </div>
                                <div class="project-name">
                                    Own Your Own Business
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="<%= asset_path("getripped.jpeg") %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">

                                </div>
                                <div class="project-name">
                                    Get Ripped
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="<%= asset_path("survivor.jpg") %> " class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">

                                </div>
                                <div class="project-name">
                                    Become a Reality TV Star
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="<%= asset_path("guitar.jpg") %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">

                                </div>
                                <div class="project-name">
                                    Learn to Play Guitar
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="<%= asset_path("google.jpg") %>" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">

                                </div>
                                <div class="project-name">
                                    Work at Google
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>What are you waiting for?</h2>
                <% if current_user %>
                  <%= link_to "My Dashboard", current_user, :class => "btn btn-default btn-xl wow tada" %>
                <% else %>
                  <a href="/users/new" class="btn btn-default btn-xl wow tada">Start achieving your goals</a>
                <% end %>
            </div>
        </div>
    </aside>



    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Contact</h2>
                    <hr class="primary">
                    <p>Ready to get started but have questions? Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x wow bounceIn"></i>
                    <p>305-555-1212</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:your-email@your-domain.com">support@wynning.co</a></p>
                </div>
            </div>
        </div>
    </section>
    <span id="HLGLink"></span>
    <span id="HLGLink2"></span>
    <span id="HLGclose"></span>
    <span id="HLGcomplete"></span>
    <span id="HLGdone"></span>
    <span id="OMGcomplete"></span>
    <span id="OMGdone"></span>
    <span id="ACTcomplete"></span>
    <span id="ACTdone"></span>

app/views/welcome/index2.html.erb
<!-- <h1>Hello World</h1> -->

<%# if current_user %>
    <!-- <p id="login">Welcome, <%#= current_user.first_name.capitalize %>  |  <%#= link_to "Log out", logout_path, method: "delete" %></p> -->
<%# else %>
  <!-- <ul> -->
    <!-- <p id="login"><%#= link_to "Login Loser", new_session_path %>  |  <%#= link_to "Signup", new_user_path %></p> -->
  <!-- </ul> -->
<%# end %>



<%# @stream.each do |key, value| %>
  <!-- <p><%#= value.first_name %> completed -->
  <!-- <%#= key.title %> <%#= time_ago_in_words(key.updated_at)%> ago</p> -->
  <%# end %>



  <% @stream.each do |key, value| %>
    <p><%= value[1].first_name %> completed
    <%= value[0].title %> <%= time_ago_in_words(value[0].created_at)%> ago</p>
    <% end %>

app/views/welcome/landing.html.erb
<div id="title" class="slide header">
  <h1><em>W</em>YNNING</h1>
  <h3>Wynning at life, 15 minutes at a time.</h3>

</div>



<div id="slide1" class="slide">
  <div class="title">
    <h1>Welcome to Wynning!</h1>
    <p>Wynning works perfectly with your busy lifestyle. It's easy to begin. Spend 15 minutes a day of focused, dedicated time towards your dreams and you will reach your goals in no time!
  </div>
</div>

<div id="slide2" class="slide">
  <div class="title">
    <h1>Customized by you, for you</h1>
    <p>You decide what steps you take to reach your goals. We help you break your goal down into small manageable steps that you can do in as little as 15 minutes a day.
    </p>
  </div>
  <img src="http://freedomforce.com/wp-content/uploads/2015/05/house-purchase.jpg">
  <img src="http://blog.jbutlerpropertymgmt.com/wp-content/uploads/2013/11/save-money.jpg">
</div>

<div id="slide3" class="slide">
  <div class="title">
    <h1>Dreams do come true!</h1>
    <p>What is your dream? Do you want to get in the best shape of your life, buy your first home, save for a dream vacation, start your own business?</p>
  </div>
</div>

<div id="slide4" class="slide header">
  <h1><em>W</em>YNNING</h1>
  <h2>So many people are living your dream.</h2>
  <h2>Don't you think it's time to join them?</h2>
</div>

app/views/welcome/stream.html.erb
<!-- <h1>Hello World</h1> -->

<%# if current_user %>
    <!-- <p id="login">Welcome, <%#= current_user.first_name.capitalize %>  |  <%#= link_to "Log out", logout_path, method: "delete" %></p> -->
<%# else %>
  <!-- <ul> -->
    <!-- <p id="login"><%#= link_to "Login Loser", new_session_path %>  |  <%#= link_to "Signup", new_user_path %></p> -->
  <!-- </ul> -->
<%# end %>



<%# @stream.each do |key, value| %>
  <!-- <p><%#= value.first_name %> completed -->
  <!-- <%#= key.title %> <%#= time_ago_in_words(key.updated_at)%> ago</p> -->
  <%# end %>

  <div id="stream_heading">
    <h1>Wynner's Circle</h1>
  </div>
    <% @stream.each do |key, value| %>
    <div class="col-lg-3"></div>
    <div class="container">
    <div class="col-lg-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-1">
                        <i class="fa fa-bullhorn fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-left stream_content">
                        <div class="huge" style="font-size:35px"><%= value[1].first_name %> <%= value[1].last_name %> </div>
                        <div style="font-size:25px">Completed: <%= value[0].title %> <%= time_ago_in_words(value[0].updated_at)%> ago!</div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  <% end %>

  <span id="HLGLink"></span>
  <span id="HLGLink2"></span>
  <span id="HLGclose"></span>
  <span id="HLGcomplete"></span>
  <span id="HLGdone"></span>
  <span id="OMGcomplete"></span>
  <span id="OMGdone"></span>
  <span id="ACTcomplete"></span>
  <span id="ACTdone"></span>